### ISSUE TITLE
 Couldn't open file INV:1989-01-01_12 

### ISSUE THREAD

**Issue by 3411457** [coecms/wps-era#1]
Hi there, I am using make file to prepare files for WRF. All things going well except invariant data, however, there is no inv foler generated or INV file linked to. I am unable to identify the problem so could you please help?

**Comment by ScottWales** [comment]
Thanks for the bug report - the makefile was missing a dependency on the invariant files, so they were never created. I've added this dependency back in, please let us know if there are any further problems
